# Generated by Django 4.2.4 on 2023-10-09 00:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, height_field='image_height', null=True, upload_to='images/profiles/', verbose_name='Profile picture', width_field='image_width')),
                ('phone_number', models.CharField(blank=True, help_text='Phone number in the format (123)-456-7890.', max_length=15, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Enter a valid phone number in the format (123)-456-7890.', regex='/\\(?([0-9]{3})\\)?([ .-]?)([0-9]{3})\\2([0-9]{4})/')], verbose_name='Phone number')),
                ('address', models.CharField(blank=True, max_length=15, verbose_name='Address')),
                ('birthdate', models.DateField(blank=True, verbose_name='Birthdate')),
                ('updated_at', models.DateTimeField(blank=True, verbose_name='Updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
